### ISSUE TITLE
Issue when deployed to SharePoint online appcatalog

### ISSUE THREAD

**Issue by jsiegmund** [OfficeDev/Word-Add-in-ClauseLibrary-Code-Sample#1] opened 2016-02-23 13:32 UTC
I've cloned the sample an got it working locally. Then I published the application to an azure website, still working fine. Now I've updated the app manifest file to use the https azure website URL and published that to a SharePoint Online appcatalog site collection. The add-in becomes visible in Word Online and when I open it, it loads. But the task pane seems to remain in some kind of loading state, being grayed out. This lasts for a couple of seconds and then changed to displaying an error that the add-in could not be loaded: 

"Add-in Error Something went wrong and we couldn't start this add-in. Please try again later or contact your system administrator". 

It's almost as if Word Online is waiting to the add-in to fire something like a "ready" event but it doesn't do so? I see the "loading" indicator thingy spinning for about 10 seconds before it errors out. I also see the entire thing loading behind the grayed mask though, all data is there and everything.

**Comment by Rick-Kirkham** [comment] 2017-01-18 19:07
Sorry we did not respond to this sooner. We will try to reproduce this issue and report back here soon.

**Comment by jsiegmund** [comment] 2017-01-18 22:03
Not sure whether this is still relevant, but thanks anyway. I might have an opportunity for using the library once again so would be useful anyway to know :)

**Comment by Rick-Kirkham** [comment] 2017-01-21 02:15
I can reproduce this, although the error message is a little different. As @jsiegmund noted, it occurs when the manifest is published to a SharePoint catalog. It does not matter if the add-in is hosted in localhost or on Azure. I had no problems when the manifest is in a network share.

Symptoms vary depending on whether using Word in O365 or desktop Word:

- **O365**: Essentially the same as @jsiegmund described. Except that since he created the issue, the add-in has been updated to use add-in commands. So now, when it is loaded, the task pane does not immediately attempt to open. Instead a button named **Open** appears in a new **Clause Library** group on the **Home** ribbon. Pressing this button gets an error box in the middle of the screen that says "Sorry, but we can't start this add-in because it isn't set up properly."

- **Desktop**: When you press the **Open** button, you get a yellow error box at the top of the screen that says "The add-in could not be started. Close this dialog to ignore the problem or click 'Restart' to try again." Clicking **Restart** just recycles the same message. Closing the dialog leave an empty task pane.
(NOTE: To load the add-in in desktop Word, you have to be logged into Word (right-side of the title bar) as an O365 user with access to the SharePoint Online catalog. I'm a tenant admin. I don't know how much less access to the catalog would be sufficient. Add the catalog as a trusted catalog to Word.) 

I will consult with the product team and report back here in the near future.

**Comment by Rick-Kirkham** [comment] 2017-01-25 18:42
I can reproduce these exact symptoms with the sample Word Add-in that Visual Studio creates when you create a Word Add-in project. I am in touch with the product team and I will create a bug as needed. In the meantime, since the problem isn't really with this sample, but with publishing in a SharePoint catalog, I am closing this issue.

**Closed as completed by Rick-Kirkham** 2017-01-25 18:42 UTC

**Comment by cebrotea** [comment] 2017-02-14 12:55
Hi Rick, any update on this or a link to the bug ?
Thanks

**Comment by Rick-Kirkham** [comment] 2017-02-14 19:35
@cebrotea
Never heard back from the product team, but I worked with this some more this morning and got it working. There are two problems that arise when the add-in manifest is loaded from a SharePoint catalog:

1. Changes were made to the app  manifest file in the last commit (Jan. 9th 2017) to support add-in commands, specifically a button on the ribbon that opens the task pane. SharePoint online catalogs don't yet support add-in manifests with this new markup (even though the manifest will have "Yes" in the "Is valid" column for the manifest). So, one thing that is required to get this sample to run from a manifest in an SPO catalog is to revert to the app manifest file before that commit.
2. There is an additional setup step needed when you want to put the manifest in an SPO catalog. There are places in the manifest where the placeholder **~remoteAppUrl** appears. When you press F5 in VS, this gets replaced with the actual IIS domain, usually something like **https://localhost:44301**. But if you are going to upload the manifest to an SPO catalog, you first have to manually replace the placeholder with the actual domain of the add-in before you upload the manifest. If you are running the sample on IIS by pressing F5 in VS, then replace the placeholder with the string "https://localhost:57697" before you put it in the catalog.
